repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: end-of-file-fixer
        exclude: /(migrations|_pb2|pycoin|deprecated)/
        files: .*.py$
    -   id: trailing-whitespace
        exclude: /(migrations|_pb2|pycoin|deprecated)/
        files: .*.py$
    -   id: file-contents-sorter
        files: ^(requirements.*.txt)$

-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.2
    hooks:
    -   id: bandit
        language_version: python3
        exclude: /(migrations|_pb2|pycoin|deprecated)/
        args: [ -r,  -c ,".bandit_scan.cfg", -f , "txt",  -o , "bandit_scan.log",  --baseline, ".bandit_baseline.json" , $(git ls-files) ]
        additional_dependencies: ["importlib-metadata==4.13.0"]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
